### ISSUE TITLE
file not found error

### ISSUE THREAD

**Issue by kompre** [alemartinello/src-files-network#3]
lo script è installato e funziona con il test descritto nel read me

ho provato a utilizzarlo su un'altra cartella, ma ricevo un file not found error

```
(.venv) kompre@SpongeBob:/mnt/c/Users/Stefano/Documents/PYTHON/DOMOTICA$ python -m srcfilesnetwork .
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/c/Users/Stefano/Documents/PYTHON/src-files-network/.venv/lib/python3.8/site-packages/srcfilesnetwork.py", line 225, in <module>
    plotnetwork()
  File "/mnt/c/Users/Stefano/Documents/PYTHON/src-files-network/.venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__     
    return self.main(*args, **kwargs)
  File "/mnt/c/Users/Stefano/Documents/PYTHON/src-files-network/.venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/mnt/c/Users/Stefano/Documents/PYTHON/src-files-network/.venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/c/Users/Stefano/Documents/PYTHON/src-files-network/.venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/mnt/c/Users/Stefano/Documents/PYTHON/src-files-network/.venv/lib/python3.8/site-packages/srcfilesnetwork.py", line 221, in plotnetwork
    plot_network(path, saveas=saveas)
  File "/mnt/c/Users/Stefano/Documents/PYTHON/src-files-network/.venv/lib/python3.8/site-packages/srcfilesnetwork.py", line 203, in plot_network
    nt.set_options(get_pyvis_options())
  File "/mnt/c/Users/Stefano/Documents/PYTHON/src-files-network/.venv/lib/python3.8/site-packages/srcfilesnetwork.py", line 178, in get_pyvis_options
    with (Path(__file__).parent.absolute() / "opt/pyvis_options.json").open() as f:
  File "/usr/lib/python3.8/pathlib.py", line 1218, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1074, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Users/Stefano/Documents/PYTHON/src-files-network/.venv/lib/python3.8/site-packages/opt/pyvis_options.json'
```

**Comment by alemartinello** [comment]
@kompre

Try the new branch, with the active .venv

```shell
git checkout -b issue-3-file_not_found_error origin/issue-3-file_not_found_error
pip install .
cd ..domotica
python -m srcfilesnetwork .
```

**Comment by kompre** [comment]
it works
